name: run daily

on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt
      - name: Run the script
        run: python main.py
        env: 
          METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          TOURNAMENT_ID: ${{ vars.TOURNAMENT_ID }}
          API_BASE_URL: ${{ vars.API_BASE_URL }}
      - name: Upload logs
        if: always()  # This ensures logs are uploaded even if the script fails
        uses: actions/upload-artifact@v3
        with:
          name: forecaster-logs
          path: logs/
          retention-days: 90  # Adjust as needed
