name: run daily

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt
      - name: Run the script
        run: python main.py
        env: # Or as an environment variable
          METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TOURNAMENT_ID: ${{ vars.TOURNAMENT_ID }}
          API_BASE_URL: ${{ vars.API_BASE_URL }}
